apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: microservices-demo
data:
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-service:8082"
  CATALOG_SERVICE_URL: "http://catalog-service:8083"
  ORDER_SERVICE_URL: "http://order-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
