apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-users-data
  labels:
    app: microservices-demo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard  # укажите класс в OpenShift при необходимости
