apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-catalog-data
  labels:
    app: microservices-demo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
